# Generated by Django 4.2.3 on 2024-01-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="min_order_price_for_free_shipping",
            field=models.DecimalField(
                decimal_places=2, default=2000.0, max_digits=6, verbose_name="minimum order price for free shipping, $"
            ),
        ),
    ]
