# Generated by Django 4.2.3 on 2024-01-23 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productimport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimport",
            options={"verbose_name": "Импорт продукта", "verbose_name_plural": "Импорт продуктов"},
        ),
    ]
