# Generated by Django 4.2.3 on 2024-01-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0002_order_total_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_number", models.CharField(max_length=9)),
                ("is_success", models.BooleanField(null=True)),
                ("order_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orders.order")),
            ],
            options={
                "verbose_name": "Оплата заказа",
                "verbose_name_plural": "Оплата заказов",
            },
        ),
    ]
