# Generated by Django 4.2.3 on 2024-01-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="итоговая цена"),
        ),
    ]
